apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc
      role: api
  template:
    metadata:
      labels:
        app: svc
        role: api
    spec:
      containers:
        - name: auth
          image: microservice-v1:latest
          ports:
            - containerPort: 9000
          command:
            - sh
            - -c
            - /app/apisrv -auth-host=$auth_host
          env:
            - name: auth_host
              value: auth-service:9001


---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: svc
    role: api

